old_sound_rabbit_mq:
    connections:
        default:
            host:     'localhost'
            port:     5672
            user:     'guest'
            password: 'guest'
            vhost:    '/'
            lazy:     false
            connection_timeout: 3
            read_write_timeout: 3

            keepalive: false
            heartbeat: 0
            use_socket: true
        another:
            url: 'amqp://guest:password@localhost:5672/vhost?lazy=1&connection_timeout=6'
    producers:
        image_data_saving:
            connection: default
            exchange_options:
                name: images
                type: direct
    consumers:
        image_data_saving:
            connection:       default
            exchange_options: {name: 'images', type: direct}
            queue_options:    {name: 'images'}
            callback:         saver_service